development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: sangam_development

test:
  adapter: test

production:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "solid_cable" %>
  url: <%= ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: sangam_production
  connects_to:
    database:
      writing: cable
  polling_interval: 1.0.seconds
  message_retention: 1.day
