default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: face_book_full_stack_development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: face_book_full_stack_test
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    database_tasks: false   # use same DB, no separate tasks

  queue:
    <<: *primary_production
    database_tasks: false

  cable:
    <<: *primary_production
    database_tasks: false
    