# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/shared", under: "shared"
pin_all_from "app/javascript/posts", under: "posts"
pin_all_from "app/javascript/profiles", under: "profiles"
pin "posts_interactions", to: "posts_interactions.js"
pin "@rails/actioncable", to: "@rails--actioncable.js" # @8.1.300
pin_all_from "app/javascript/channels", under: "channels"
pin_all_from "app/javascript/chat", under: "chat"
pin "notifications", to: "notifications.js"
pin "reels", to: "reels.js"
pin "stories",   to: "stories.js"
pin "bookmarks", to: "bookmarks.js"
pin "groups",    to: "groups.js"
pin "events",    to: "events.js"
pin "dark_mode",          to: "dark_mode.js"
pin "link_preview",       to: "link_preview.js"
pin "collections",        to: "collections.js"
pin "story_interactions", to: "story_interactions.js"
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"
